#!/sbin/openrc-run

description="Xorg Server"

depend() {
	need dsme elogind
	after bootmisc rsyslog mce ofono pulseaudio-enable-autospawn
	keyword -timeout
	provide xsession
}

start() {
    einfo "Starting Xorg Server" > /dev/console
    XORG_OPTIONS="-logverbose 1 -noreset -s 0 -core"
    XDG_SESSION_TYPE=x11 /usr/sbin/dsmetool -n -8 -r "autologin user startx -- $XORG_OPTIONS"
}

stop_post() {
    if [ -d /home/user ]; then
	cp /var/log/Xorg.0.log /home/user
    fi
}
