#!/sbin/openrc-run
### BEGIN INIT INFO
# Provides:          xsession
# Required-Start:    xorg mce
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Starting Xsession
### END INIT INFO

start_pre() {
        DISPLAY=:0 /usr/sbin/waitx
}

start() {
#    if [ -e /tmp/ACT_DEAD ]; then
#        initctl emit --no-wait XSESSIONS_ACTDEAD_STARTING
#    else
#        initctl emit --no-wait XSESSIONS_STARTING
#    fi
    exec su - user /etc/X11/Xsession
}

