#!/sbin/openrc-run

description="Xorg Server"

depend() {
	need dsme mce
	after bootmisc rsyslog ofono icd2
	keyword -timeout
	provide xsession
}

start() {
    einfo "Starting Xorg Server" > /dev/console
    XORG_OPTIONS="-keeptty -logverbose 1 -noreset -s 0 -core"
    /usr/sbin/dsmetool -n -8 -r "autologin user startx -- $XORG_OPTIONS"
}

stop_post() {
    if [ -d /home/user ]; then
	cp /var/log/Xorg.0.log /home/user
    fi
}
