#!/bin/sh
set -e

usage() {
	echo "usage: dh_maemo_installicdnetwork libicd-network-tor libicd_network_tor.so WLAN_INFRA DUMMY ..." >&2
	exit 1
}

if [ -z "$(which gconftool)" ]; then
	echo "dh_maemo_installicdnetwork ERROR: gconftool not found" >&2
	exit 1
fi

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
	usage
fi

pkgname="$1"
shift
sofile="$1"
shift
postinstfile="debian/${pkgname}.postinst.debhelper"
postrmfile="debian/${pkgname}.postrm.debhelper"

user="user"
gconfpath="/system/osso/connectivity/network_type"
gconfmods="network_modules"

# postinst
cat <<EOF >> "$postinstfile"
net_args="-n \$(echo $@ | sed 's/ / -n /g')"
su ${user} -c "icd2-manage-modules -a add -m $sofile \$net_args"
EOF

# postrm
cat <<EOF >> "$postrmfile"
net_args="-n \$(echo $@ | sed 's/ / -n /g')"
su ${user} -c "icd2-manage-modules -a del -m $sofile \$net_args"
EOF
